### PR TITLE
Changes to run under Rakudo 2014.12

### PR DESCRIPTION
**Pull request by MARTIMM**
The important change lies in **class MongoDB::Connection** where the call to IO::Socket::INET **send()** is changed to **write()**. The **send()** needed a string for which the buffer **$b** must be decoded. This will corrupt the mongodb opcodes. This could be noticed by using wireshark. **Write()** however can process the buffer directly making it faster too.

The rest of the changes are in **META.info** to change the version and the **README.md** to modify the examples and changelog

### CODE REVIEW

**Comment by bbkr** [comment]
I appreciate the changes, thanks!

If you want to maintain those modules I can transfer ownership to you. Or feel free to change links to your forks in Perl 6 ecosystem.

They are one step away from being qualified as driver: IEEE754 buffer pack/unpack is missing in Rakudo but can easily be added to BSON manually, and that opens way to float numbers and server authentication. Also BSON now can get gigantic speedup from parallelization in Rakudo. And maybe Reactive Mongo based on Supplies is also within reach.

**Comment by MARTIMM** [comment]
Hi Pawel,

I would like to take over your two modules but I am very new to perl 6. It 
will take time to learn the language in full so at this moment I could only 
keep the modules runnable.
When you transfer the ownership, I must remove the fork is n"t it? I"m also 
new to git you know, only a year experience :-)

Greetings,
Marcel

**Comment by bbkr** [comment]
Yes, please remove your forks. I'll transfer repositories and update Ecosystem locations.

**Comment by MARTIMM** [comment]
Done that.

**Comment by bbkr** [comment]
Transfer requests sent. Once completed please edit:

1. Ecosystem
https://github.com/perl6/ecosystem/blob/master/META.list#L87
https://github.com/perl6/ecosystem/blob/master/META.list#L93

2. "source-url" in META.json files

3. CONTACT section in README.md files

I also:
* switched those modules to semantic versioning
* made you an official author
* made modules compatible with S11 spec

Good luck.

**Comment by MARTIMM** [comment]
On 01/12/2015 02:20 AM, Pawel Pabian wrote:
>
> Transfer requests sent. Once completed please edit:
>
> 1.
>
>     Ecosystem
>     https://github.com/perl6/ecosystem/blob/master/META.list#L87
>     https://github.com/perl6/ecosystem/blob/master/META.list#L93
>
> 2.
>
>     "source-url" in META.json files
>
> 3.
>
>     CONTACT section in README.md files
>
> I also:
>
>   * switched those modules to semantic versioning
>   * made you an official author
>   * made modules compatible with S11 spec
>
>
Think I've got everything right now.
Thanks for the pointers above because I would have forgotten that.

Bye,
Marcel

**Pull request merged**
